config/routes.rb
LiveMaps::Application.routes.draw do

  root 'datasets#index'

  match '/about', :to => "static_contents#about", via: 'get'
  match '/geo_proxy', :to => "proxy#geo_proxy", via: 'get'

  resources :datasets, :only => [:index, :show], :has_many => :customers
  resources :licences, :only => :show

  resources :map_search, only: [:index, :show]

  namespace :admin do
    match '/', :to => "datasets#index", via: 'get'
    resources :customers
    resources :licences
    resources :categories
    resources :programmes
    resources :data_categories
    resources :datasets_decisions

    resources :datasets do
      resources :datasets_decisions
    end

    resources :decisions do
      resources :categories
    end

    resources :site_links

    match 'datasets_decision/categories_for_decision/:id', :to => "datasets_decisions#categories_for_decision", via: 'get'
  end

  resources :site_links
  resources :decisions
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :dataset
  
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => "must be a valid email address"
  validates_presence_of :title,:first_name, :last_name, :email, :institution, :intended_use, :licence, :dataset
  validates_inclusion_of :licence_agreed, :in => [true], :message => 'You must agree to the data licence'
  validates_inclusion_of :understand_collaboration, :in => [true], :message => 'You must agree to explore collaboration with UNEP-WCMC in further analysis'
  validates_inclusion_of :non_commercial, :in => [true], :message => 'You must agree to not use the dataset for commercial purposes'
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::AdminController
  # GET /customers
  # GET /customers.xml
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.xml
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.xml
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.xml
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        flash[:notice] = 'Customer was successfully created.'
        format.html { redirect_to(@customer) }
        format.xml  { render :xml => @customer, :status => :created, :location => @customer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.xml
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        flash[:notice] = 'Customer was successfully updated.'
        format.html { redirect_to(@customer) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.xml
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to(customers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  # POST /customers
  def create
    @dataset = Dataset.find(params[:dataset_id])
    @customer = Customer.new(params[:customer])
    @customer.dataset = @dataset
    @customer.licence = @dataset.licence

    if @customer.save
      session["dataset_#{@dataset.id}"] = "agreed"
      redirect_to @dataset.shp_download
    else
      flash[:error] = @customer.errors.collect { |f, e| "<li><b>" + f.humanize + "</b> - " + e + "</li>"}
      redirect_to dataset_path(@dataset, {:customer => @customer.attributes})
    end
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/index.html.erb
<h1>Listing Downloaders</h1>

<table>
  <tr>
    <th>Title</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Institution</th>
    <th>Intended use</th>
    <th>Licence agreed</th>
    <th>Licence</th>
    <th>Dataset</th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%=h customer.title %></td>
    <td><%=h customer.first_name %></td>
    <td><%=h customer.last_name %></td>
    <td><%=h customer.email %></td>
    <td><%=h customer.institution %></td>
    <td><%=h customer.intended_use %></td>
    <td><%=h customer.licence_agreed %></td>
    <td><%=h Licence.find(customer.licence_id).title %></td>
    <td><%=h Dataset.find(customer.dataset_id).title %></td>
    <td><%= link_to 'Show', [:admin,customer] %></td>
  </tr>
<% end %>
</table>

<br />

app/views/admin/customers/show.html.erb
<p>
  <b>Title:</b>
  <%=h @customer.title %>
</p>

<p>
  <b>First name:</b>
  <%=h @customer.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%=h @customer.last_name %>
</p>

<p>
  <b>Email:</b>
  <%=h @customer.email %>
</p>

<p>
  <b>Institution:</b>
  <%=h @customer.institution %>
</p>

<p>
  <b>Intended use:</b>
  <%=h @customer.intended_use %>
</p>

<p>
  <b>Licence agreed:</b>
  <%=h @customer.licence_agreed %>
</p>

<p>
  <b>Licence:</b>
  <%=h @customer.licence_id %>
</p>

<p>
  <b>Dataset:</b>
  <%=h @customer.dataset_id %>
</p>


<%= link_to 'Back', admin_customers_path, :class=> "button" %>