config/routes.rb
LiveMaps::Application.routes.draw do

  root 'datasets#index'

  match '/about', :to => "static_contents#about", via: 'get'
  match '/geo_proxy', :to => "proxy#geo_proxy", via: 'get'

  resources :datasets, :only => [:index, :show], :has_many => :customers
  resources :licences, :only => :show

  resources :map_search, only: [:index, :show]

  namespace :admin do
    match '/', :to => "datasets#index", via: 'get'
    resources :customers
    resources :licences
    resources :categories
    resources :programmes
    resources :data_categories
    resources :datasets_decisions

    resources :datasets do
      resources :datasets_decisions
    end

    resources :decisions do
      resources :categories
    end

    resources :site_links

    match 'datasets_decision/categories_for_decision/:id', :to => "datasets_decisions#categories_for_decision", via: 'get'
  end

  resources :site_links
  resources :decisions
end

app/models/datasets_decision.rb
class DatasetsDecision < ActiveRecord::Base
  belongs_to :dataset
  belongs_to :decision
  belongs_to :category
  
  validates_presence_of :dataset, :decision
end

app/controllers/admin/datasets_decisions_controller.rb
class Admin::DatasetsDecisionsController < Admin::AdminController
  layout 'admin'
  # GET /datasets_decisions
  def index
    @dataset = Dataset.find params[:dataset_id]
    @datasets_decisions = @dataset.datasets_decisions
  end

  # GET /datasets_decisions/1
  def show
    @datasets_decision = DatasetsDecision.find(params[:id])
  end

  # GET /decisions/new
  # GET /decisions/new.xml
  def new
    @dataset = Dataset.find params[:dataset_id]
    @datasets_decision = DatasetsDecision.new :dataset => @dataset
    @decisions = Decision.order("name ASC")
    @categories = []

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @decision }
    end
  end

  # GET /decisions/1/edit
  def edit
    @datasets_decision = DatasetsDecision.find(params[:id])
    @decisions = Decision.all
    @categories = @datasets_decision.try(:decision).try(:categories)
    @categories ||= []
  end

  # POST /datasets_decisions
  # POST /datasets_decisions.xml
  def create
    @datasets_decision = DatasetsDecision.new(datasets_decision_params)

    respond_to do |format|
      if @datasets_decision.save
        flash[:notice] = 'Datasets > decision link was successfully created.'
        format.html { redirect_to([:admin,@datasets_decision.dataset, @datasets_decision]) }
        format.xml  { render :xml => @datasets_decision, :status => :created, :location => @datasets_decision }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @datasets_decision.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /datasets_decisions/1
  # PUT /datasets_decisions/1.xml
  def update
    @datasets_decision = DatasetsDecision.find(params[:id])

    respond_to do |format|
      if @datasets_decision.update_attributes(datasets_decision_params)
        flash[:notice] = 'DatasetsDecision was successfully updated.'
        format.html { redirect_to([:admin,@datasets_decision]) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @datasets_decision.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /datasets_decisions/1
  # DELETE /datasets_decisions/1.xml
  def destroy
    @datasets_decision = DatasetsDecision.find(params[:id])
    @dataset = @datasets_decision.dataset
    @datasets_decision.destroy

    respond_to do |format|
      format.html { redirect_to(admin_dataset_datasets_decisions_url @dataset) }
      format.xml  { head :ok }
    end
  end

  # GET the categories for the given decision
  def categories_for_decision
    @decision = Decision.find params[:id]
    @categories = @decision.categories
  end

  private

  def datasets_decision_params
    params.require(:datasets_decision).permit(:dataset_id, :category_id, :decision_id)
  end
end

app/views/admin/datasets_decisions/_category_options.html.erb
<%
if @datasets_decision.nil?
   current_category = ''
else
   current_category = @datasets_decision.category.nil? ? "" : @datasets_decision.category.id
end
%>
<%= collection_select(:datasets_decision, :category_id, @categories, :id, :name, {:selected_value => current_category, :prompt => true})%>

app/views/admin/datasets_decisions/_form.html.erb
<%= form_for([:admin,@dataset,@datasets_decision], :html => { :multipart => true }) do |f| %>
  <% if @datasets_decision.errors.any? %>
    <ul>
      <% @datasets_decision.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.hidden_field :dataset_id  %>

  <p>
    <%= f.label :decision %><br />
    <% current_dataset = @datasets_decision.dataset.nil? ? "" : @datasets_decision.dataset.id %>
    <%= collection_select(:datasets_decision, :decision_id, @decisions, :id, :name, {:selected_value => current_dataset, :prompt => true})%>
  </p>

  <p>
    <%= f.label :category %><br />
    <div id="category_select_combo"><%= render :partial => "category_options"%></div>
  </p>

  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

<script type=text/javascript>
    $("#datasets_decision_decision_id").change(function(){
        $.ajax({url: '/admin/datasets_decision/categories_for_decision/' + (this.value), type:'get', dataType: 'script' })
    });
</script>

app/views/admin/datasets_decisions/categories_for_decision.js.erb
$(function() {
    $('#category_select_combo').empty().append('<%= escape_javascript(render :partial => "category_options") %>')
})

app/views/admin/datasets_decisions/edit.html.erb
<h1>Editing dataset</h1>

<%= render :partial => 'form' %>

<%= link_to 'show', [:admin, @datasets_decision], :class=> "button" %>
<%= link_to 'Back', admin_dataset_path(@datasets_decision.dataset), :class=> "button" %>

app/views/admin/datasets_decisions/index.html.erb
<h1>Listing decisions for dataset '<%= @dataset.title %>'</h1>

<table>
  <tr>
    <th>Decision</th>
    <th>Category</th>
    <th>&nbsp;</th>
  </tr>

<% @datasets_decisions.each do |datasets_decision| %>
  <tr>
    <td><%= datasets_decision.decision.name %></td>
    <td><%= datasets_decision.category.try(:name) %></td>
    <td>
      <%= link_to 'Show', [:admin, datasets_decision] %>
      <%= link_to 'Edit', edit_admin_datasets_decision_path(datasets_decision) %>
      <%= link_to 'Destroy', [:admin,datasets_decision], :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New datasets_decision', new_admin_dataset_datasets_decision_path(@dataset), :class=> "button" %>

app/views/admin/datasets_decisions/new.html.erb
<h1>New dataset</h1>

<%= render :partial => 'form' %>

<%= link_to 'Back', admin_datasets_path, :class=> "button" %>

app/views/admin/datasets_decisions/show.html.erb
<p>
  <b>Dataset</b>
  <%=h @datasets_decision.dataset.title %>
</p>

<p>
  <b>Decision</b>
  <%=h @datasets_decision.decision.name %>
</p>

<p>
  <b>Category</b>
  <%=h @datasets_decision.category.try(:name) %>
</p>

<%= link_to 'Edit', edit_admin_datasets_decision_path(@datasets_decision), :class=> "button" %>
<%= link_to 'Back', admin_dataset_datasets_decisions_path(@datasets_decision.dataset), :class=> "button" %>