config/routes.rb
LiveMaps::Application.routes.draw do

  root 'datasets#index'

  match '/about', :to => "static_contents#about", via: 'get'
  match '/geo_proxy', :to => "proxy#geo_proxy", via: 'get'

  resources :datasets, :only => [:index, :show], :has_many => :customers
  resources :licences, :only => :show

  resources :map_search, only: [:index, :show]

  namespace :admin do
    match '/', :to => "datasets#index", via: 'get'
    resources :customers
    resources :licences
    resources :categories
    resources :programmes
    resources :data_categories
    resources :datasets_decisions

    resources :datasets do
      resources :datasets_decisions
    end

    resources :decisions do
      resources :categories
    end

    resources :site_links

    match 'datasets_decision/categories_for_decision/:id', :to => "datasets_decisions#categories_for_decision", via: 'get'
  end

  resources :site_links
  resources :decisions
end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
  has_many :customers
  has_many :datasets_decisions, dependent: :destroy
  has_many :decisions, through: :datasets_decisions
  belongs_to :programme
  has_and_belongs_to_many :data_categories
  has_and_belongs_to_many :observation_types
  has_and_belongs_to_many :data_formats

  include DatasetFixedFieldsValidation
  include PgSearch

  pg_search_scope :search_by_text, :using => { :tsearch => {:prefix => true} },
    :against => [:title, :tags]

  validates_presence_of :title, :short_desc, :long_desc, :metadata_description
  validates_format_of :wms_server, :wfs, :meta_download, :with => /\A((http|https):\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z0-9]{1,5}(:[0-9]{1,5})?(\/.*)?\z/, :allow_blank => true

  before_save :strip_urls

  accepts_nested_attributes_for :data_categories
  accepts_nested_attributes_for :observation_types
  accepts_nested_attributes_for :data_formats

  has_attached_file :factsheet
  do_not_validate_attachment_file_type :factsheet

  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "400x400>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  attr_accessor :delete_image
  before_save -> { image.clear if delete_image == '1' }

  def tags_array
    tags.join(',')
  end

  def tags_array=(params)
    self.tags = params.gsub(' ', '').split(',')
    self.save
  end

  def recently_updated?
    self.updated_at > 30.days.ago && self.updated_at != self.created_at
  end

  def recently_created?
    self.created_at > 30.days.ago
  end

  private

  def strip_urls
    [wms_name, wms_server].each {|s| s.try(:strip!)}
  end
end

app/controllers/admin/datasets_controller.rb
class Admin::DatasetsController < Admin::AdminController
  inject :dataset, :data_categories, :data_formats, :observation_types, :geographical_ranges, :programmes
  helper_method :data_categories, :data_formats, :observation_types, :geographical_ranges, :programmes

  before_action :get_existing_tags, only: [:new, :edit]

  # GET /datasets
  # GET /datasets.xml
  def index
    @datasets = Dataset.all.order("order_number ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @datasets }
    end
  end

  # GET /datasets/1
  # GET /datasets/1.xml
  def show
    @dataset = dataset
    @linked_decisions = @dataset.datasets_decisions

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dataset }
    end
  end

  # GET /datasets/new
  # GET /datasets/new.xml
  def new
    @dataset = Dataset.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dataset }
    end
  end

  # GET /datasets/1/edit
  def edit
    @dataset = dataset
  end

  # POST /datasets
  # POST /datasets.xml
  def create
    @dataset = Dataset.new(dataset_params)

    respond_to do |format|
      if @dataset.save
        flash[:notice] = 'Dataset was successfully created.'
        format.html { redirect_to([:admin,@dataset]) }
        format.xml  { render :xml => @dataset, :status => :created, :location => @dataset }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dataset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /datasets/1
  # PUT /datasets/1.xml
  def update
    @dataset = dataset

    respond_to do |format|
      if @dataset.update_attributes!(dataset_params)
        flash[:notice] = 'Dataset was successfully updated.'
        format.html { redirect_to([:admin,@dataset]) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dataset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /datasets/1
  # DELETE /datasets/1.xml
  def destroy
    @dataset = dataset
    @dataset.destroy

    respond_to do |format|
      format.html { redirect_to(admin_datasets_url) }
      format.xml  { head :ok }
    end
  end

  private

  def get_existing_tags
    @tags = Dataset.pluck(:tags).flatten.compact.uniq.sort || []
  end

  def dataset_params
    params.require(:dataset).permit(:title, :short_desc, :long_desc, :tags_array,
      :metadata_description, :shp_download, :wms_server, :wfs, :meta_download,
      :licence_desc, :wms_name, :styles, :view_params, :arcgis_link, :order_number,
      :has_legend, :html, :xml, :factsheet, :creation_date, :time_range_start,
      :time_range_end, :data_provider, :geographical_range, :image, :delete_image,
      :layer_color, :factsheet_url, :version, :programme_id,
      data_category_ids: [], observation_type_ids: [], data_format_ids: [])
  end
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  inject :data_categories, :data_formats, :observation_types, :geographical_ranges
  helper_method :data_categories, :data_formats, :observation_types, :geographical_ranges

  # GET /datasets
  def index
    @search = MapSearch.new(sort_by: 'creation_date')
    @decisions = Decision.where(:parent_id => nil).order("order_number ASC")
  end

  # GET /datasets/1
  def show
    @dataset = DatasetPresenter.new(Dataset.find(params[:id]))
    @customer = Customer.new(params[:customer])
  end
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/views/admin/datasets/_form.html.erb
<%= form_for([:admin, @dataset], :html => { :multipart => true }) do |f| %>
  <% if @dataset.errors.any? %>
    <ul>
      <% @dataset.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title, class: 'long-text' %>
  </p>

  <p>
    <%= f.label :tags_array, 'Alternate Search Keywords' %><br />
    <%= f.text_area :tags_array, class: 'tag-field', data: {tags: @tags.try(:map) {|t| {id: t, text: t}} } %><br>
    <i>Tag this dataset with alternate keywords that will be picked up on in the search</i>
  </p>

  <p>
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </p>

  <p>
    <%= f.label :order_number %><br />
    <%= f.text_field :order_number %>
  </p>

  <p>
    <%= f.label :short_desc %><br />
    <%= f.text_area :short_desc %>
    <br /><small>To add links, use the format "text":http://example.com</small>
  </p>

  <p>
    <%= f.label :long_desc %><br />
    <%= f.text_area :long_desc %>
    <br /><small>To add links, use the format "text":http://example.com</small>
  </p>

  <p>
    <%= f.label 'Citation' %><br />
    <%= f.text_area :metadata_description %>
    <br /><small>To add links, use the format "text":http://example.com</small>
  </p>

  <p>
    <%= f.label 'Publication date' %><br/>
    <%= f.number_field :creation_date, step: 1, in: 1900...Time.now.year+1 %>
  </p>

  <p>
    <%= f.label :time_range_start, 'Time range' %><br/>
    <%= f.number_field :time_range_start, step: 1, in: 1900...Time.now.year+1 %>
    -
    <%= f.number_field :time_range_end, step: 1, in: 1900...Time.now.year+1 %>
  </p>

  <p class="options">
    <%= f.label :programme %><br/>
    <%= f.collection_select :programme_id, Programme.all, :id, :name %>
  </p>

  <p class="options">
    <%= f.label :data_categories %><br/>
    <%= f.collection_check_boxes :data_category_ids, data_categories, :id, :name %>
  </p>

  <p class="options radio">
    <%= f.label :format, 'Data format' %><br/>
    <%= f.collection_check_boxes :data_format_ids, data_formats, :id, :name %>
  </p>

  <p class="options radio">
    <%= f.label 'Data types:' %><br/>
    <%= f.collection_check_boxes :observation_type_ids, observation_types, :id, :name %>
  </p>

  <p class="options radio">
    <%= f.label :geographical_range %><br/>
    <% geographical_ranges.each do |option| %>
      <%= f.radio_button :geographical_range, option.id %>
      <%= f.label :geographical_range, option.name.humanize, value: option.id %>
    <% end %>
  </p>

  <p>
    <%= f.label :data_provider %><br/>
    <%= f.text_field :data_provider %>
  <p>

  <p>
    <%= f.label 'Metadata file' %><br/>
    <%= f.file_field :factsheet %>
  </p>

  <p>
    <%= f.label 'Factsheet' %><br/>
    <%= f.text_field :factsheet_url %>
  </p>

  <p>
    <%= f.label :shp_download %><br />
    <%= f.text_field :shp_download, class: 'long-text' %>
  </p>

  <p>
    <%= f.label :arcgis_link %><br />
    <%= f.text_field :arcgis_link, class: 'long-text' %>
  </p>

  <p>
    <%= f.label :wms_server %><br />
    <%= f.text_field :wms_server, class: 'long-text' %>
  </p>

  <p>
    <%= f.label :wms_name %><br />
    <%= f.text_field :wms_name %>
  </p>

  <p>
    <%= f.label :styles, label: 'Map Style Parameter' %><br />
    <%= f.text_field :styles %>
  </p>

  <p>
    <%= f.label :view_params %><br />
    <%= f.text_field :view_params %>
  </p>

  <p>
    <%= f.label :layer_color %><br />
    <%= f.text_field :layer_color, type: 'color' %>
  </p>

  <p>
    <%= f.label :wfs %><br />
    <%= f.text_field :wfs %>
  </p>
  <p>
    <%= f.label :meta_download %><br />
    <%= f.text_field :meta_download %>
  </p>

  <p>
    <%= f.label :has_legend %><br />
    <%= f.check_box :has_legend %>
  </p>

  <p>
    <%= f.label 'Use constraints' %><br />
    <%= f.text_area :licence_desc %>
    <br /><small>To add links, use the format "text":http://example.com</small>
  </p>

  <p>
    <%= f.label :image %><br />
    <%= f.file_field :image %><br/>
    <small>Current image:</small>
    <%= image_tag @dataset.image.url if @dataset.image.present? %>
  </p>

  <p>
  <%= f.label :delete_image %><br />
    <%= f.check_box :delete_image %>
  </p>

  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/admin/datasets/edit.html.erb
<h1>Editing dataset</h1>

<%= render partial: 'form' %>

<%= link_to 'View or edit Decision Associations', admin_dataset_datasets_decisions_path(@dataset), :class=> "button" %>
<%= link_to 'Show', [:admin, @dataset], :class=> "button" %>
<%= link_to 'Back', admin_datasets_path, :class=> "button" %>

app/views/admin/datasets/index.html.erb
<h1>Listing datasets</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Order Number</th>
    <th>Short desc</th>
    <th>WMS Name</th>
    <th>&nbsp;</th>
  </tr>

<% @datasets.each do |dataset| %>
  <tr>
    <td><%= dataset.title %></td>
    <td><%= dataset.order_number %></td>
    <td><%= truncate(dataset.short_desc,lenght:30) %></td>
    <td><%= truncate(dataset.wms_name,lenght:30) %></td>
    <td><%= link_to 'Show', [:admin, dataset] %>
    <%= link_to 'Edit', edit_admin_dataset_path(dataset) %>
    <%= link_to 'Destroy', [:admin,dataset], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New dataset', new_admin_dataset_path, :class=> "button" %>

app/views/admin/datasets/new.html.erb
<h1>New dataset</h1>

<%= render partial: 'form' %>

<%= link_to 'Back', admin_datasets_path, :class=> "button" %>

app/views/admin/datasets/show.html.erb
<p>
  <b>Title:</b>
  <%=h @dataset.title %>
</p>

<p>
  <b>Alternative Search Keywords:</b>
</p>
<p>
  <% @dataset.tags.each do |tag| %>
    <span class="tag"><%= tag %></span>
  <% end %>
</p>

<p>
  <b>Version:</b>
  <%= @dataset.version %>
</p>

<p>
  <b>Short desc:</b>
  <%= RedCloth.new(@dataset.short_desc).to_html.html_safe %>
</p>

<p>
  <b>Long desc:</b>
  <%= RedCloth.new(@dataset.long_desc).to_html.html_safe %>
</p>

<p>
  <b>Citation:</b>
  <%= RedCloth.new(@dataset.metadata_description).to_html.html_safe %>
</p>

<p>
  <b>Shp download:</b>
  <%=h @dataset.shp_download %>
</p>

<p>
  <b>Arcgis.com link:</b>
  <%=h @dataset.arcgis_link %>
</p>

<p>
  <b>Wms server:</b>
  <%=h @dataset.wms_server %>
</p>

<p>
  <b>Wms name:</b>
  <%=h @dataset.wms_name %>
</p>

<p>
  <b>Styles:</b>
  <%=h @dataset.styles %>
</p>

<p>
  <b>View params:</b>
  <%=h @dataset.view_params %>
</p>

<p>
  <b>Wfs:</b>
  <%=h @dataset.wfs %>
</p>

<p>
  <b>Meta download:</b>
  <%=h @dataset.meta_download %>
</p>

<p>
  <b>Factsheet:</b>
  <%=h @dataset.factsheet_url %>
</p>

<p>
  <b>Has Legend?:</b>
  <%=h @dataset.has_legend? %>
</p>

<p>
  <b>Use constraints:</b>
  <%=h @dataset.licence_desc %>
</p>

<p>
  <b>Publication date:</b>
  <%= @dataset.creation_date %>
</p>

<p>
  <b>Time range:</b>
  <%= @dataset.time_range_start %>-<%= @dataset.time_range_end %>
</p>

<p>
  <b>Programme:</b>
  <%= @dataset.programme.name %>
</p>

<p>
  <b>Data categories:</b>
  <%= @dataset.data_categories.map(&:name).map(&:capitalize).join(', ') %>
</p>

<p>
  <b>Formats:</b>
  <%= @dataset.data_formats.map(&:name).map(&:capitalize).join(', ') %>
</p>

<p>
  <b>Geographical range:</b>
  <%= @dataset.geographical_range.to_s.capitalize %>
</p>


<p>
  <b>Data types:</b>
  <%= @dataset.observation_types.map(&:name).map(&:capitalize).join(', ') %>
</p>


<%= link_to 'Edit', edit_admin_dataset_path(@dataset), :class=> "button" %>
<%= link_to 'Back', admin_datasets_path, :class=> "button" %>
<br />
<br />
<br />
<br />

<h3 style="border-top: 2px solid #3174AF; margin-bottom:0em;">Linked Desicions</h3>
<%= link_to 'Link to another decision', new_admin_dataset_datasets_decision_path(@dataset), :class=> "button" %>
<table>
  <tr>
    <th>Decision</th>
    <th>Category</th>
    <th>&nbsp;</th>
  </tr>

<% @linked_decisions.each do |datasets_decision| %>
  <tr>
    <% if datasets_decision.decision %>
      <td><%= link_to datasets_decision.decision.name, [:admin, datasets_decision.decision] %></td>
      <td><%= (link_to datasets_decision.category.try(:name), [:admin, datasets_decision.category]) if datasets_decision.category.present? %></td>
      <td>
        <%= link_to 'Show', [:admin, datasets_decision] %>
        <%= link_to 'Edit', edit_admin_datasets_decision_path(datasets_decision) %>
        <%= link_to 'Destroy', [:admin,datasets_decision], :confirm => 'Are you sure?', :method => :delete %>
      </td>
    <% end %>
  </tr>
<% end %>
</table>