config/routes.rb
LiveMaps::Application.routes.draw do

  root 'datasets#index'

  match '/about', :to => "static_contents#about", via: 'get'
  match '/geo_proxy', :to => "proxy#geo_proxy", via: 'get'

  resources :datasets, :only => [:index, :show], :has_many => :customers
  resources :licences, :only => :show

  resources :map_search, only: [:index, :show]

  namespace :admin do
    match '/', :to => "datasets#index", via: 'get'
    resources :customers
    resources :licences
    resources :categories
    resources :programmes
    resources :data_categories
    resources :datasets_decisions

    resources :datasets do
      resources :datasets_decisions
    end

    resources :decisions do
      resources :categories
    end

    resources :site_links

    match 'datasets_decision/categories_for_decision/:id', :to => "datasets_decisions#categories_for_decision", via: 'get'
  end

  resources :site_links
  resources :decisions
end

app/models/decision.rb
class Decision < ActiveRecord::Base
  has_many :datasets_decisions, dependent: :destroy
  has_many :datasets, :through => :datasets_decisions
  has_many :categories
  has_many :children, :class_name => 'Decision', :foreign_key => 'parent_id'
  belongs_to :parent, :class_name => 'Decision'

  validates_presence_of :name, :short_name

  scope :roots, -> { where(parent_id: nil) }
end

app/controllers/admin/decisions_controller.rb
class Admin::DecisionsController < Admin::AdminController
  # GET /decisions
  # GET /decisions.xml
  def index
    @decisions = Decision.all.order("order_number ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @decisions }
    end
  end

  # GET /decisions/1
  # GET /decisions/1.xml
  def show
    @decision = Decision.find(params[:id])
    @categories = @decision.categories

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @decision }
    end
  end

  # GET /decisions/new
  # GET /decisions/new.xml
  def new
    @decision = Decision.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @decision }
    end
  end

  # GET /decisions/1/edit
  def edit
    @decision = Decision.find(params[:id])
  end

  # POST /decisions
  # POST /decisions.xml
  def create
    @decision = Decision.new(decision_params)

    respond_to do |format|
      if @decision.save
        flash[:notice] = 'Decision was successfully created.'
        format.html { redirect_to([:admin,@decision]) }
        format.xml  { render :xml => @decision, :status => :created, :location => @decision }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @decision.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /decisions/1
  # PUT /decisions/1.xml
  def update
    @decision = Decision.find(params[:id])

    respond_to do |format|
      if @decision.update_attributes(decision_params)
        flash[:notice] = 'Decision was successfully updated.'
        format.html { redirect_to([:admin,@decision]) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @decision.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /decisions/1
  # DELETE /decisions/1.xml
  def destroy
    @decision = Decision.find(params[:id])
    @decision.destroy

    respond_to do |format|
      format.html { redirect_to(admin_decisions_url) }
      format.xml  { head :ok }
    end
  end

  private

  def decision_params
    params.require(:decision).permit(:name, :short_name, :short_desc, :description, :parent_id, :established, :key_points, :links, :order_number)
  end
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  # GET /decisions
  def index
    @decisions = Decision.all
  end

  # GET /decisions/1
  def show
    @decision = Decision.find(params[:id])
    @datasets = @decision.datasets
    @categories = @decision.categories
  end
end

app/views/admin/decisions/_form.html.erb
<%= form_for([:admin,@decision], :html => { :multipart => true }) do |f| %>
  <% if @decision.errors.any? %>
    <ul>
      <% @decision.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :order_number %><br />
    <%= f.text_field :order_number %>
  </p>
  <p>
    <%= f.label :short_name %><br />
    <%= f.text_field :short_name %>
  </p>
  <p>
    <%= f.label :established %><br />
    <%= f.text_area :established %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :key_points %><br />
    <%= f.text_area :key_points %>
  </p>
  <p>
    <%= f.label :links %><br />
    <%= f.text_area :links %>
  </p>

  <p>
    <%= f.label :group_parent %><br />
    <%= collection_select(:decision, :parent_id, Decision.order("name ASC"), :id, :name, {:prompt => true})%>
  </p>

  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/admin/decisions/edit.html.erb
<h1>Editing decision</h1>

<%= render :partial => 'form' %>

<%= link_to 'Show', [:admin, @decision], :class=> "button" %>
<%= link_to 'Back', admin_decisions_path, :class=> "button" %>

app/views/admin/decisions/index.html.erb
<h1>Listing decisions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Order Number</th>
    <th>Short Name</th>
    <th>Short Description</th>
    <th>Description</th>
    <th>&nbsp;</th>
  </tr>

<% @decisions.each do |decision| %>
  <tr>
    <td><%= decision.name %></td>
    <td><%= decision.order_number %></td>
    <td><%= truncate(decision.short_name, lenght: 30) %></td>
    <td><%= truncate(decision.short_desc, lenght: 30) %></td>
    <td><%= truncate(decision.description, lenght: 30) %></td>
    <td><%= link_to 'Show', [:admin, decision] %>
    <%= link_to 'Edit', edit_admin_decision_path(decision) %>
    <%= link_to 'Destroy', [:admin,decision], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New decision', new_admin_decision_path, :class=> "button" %>

app/views/admin/decisions/new.html.erb
<h1>New decision</h1>

<%= render :partial => 'form' %>

<%= link_to 'Back', admin_decisions_path, :class=> "button" %>

app/views/admin/decisions/show.html.erb
<h2>Decision Details</h2>
<p>
  <b>Name</b>
  <%= h @decision.name %>
</p>
<p>
  <b>Short name</b>
  <%= h @decision.short_name %>
</p>
<p>
  <b>Short desc</b>
  <%= h @decision.short_desc %>
</p>
<p>
  <b>Description</b>
  <%= h @decision.description %>
</p>
<p>
  <b>Group</b>
  <% if @decision.parent.present? %>
    <%= link_to @decision.parent.name, admin_decision_path(@decision.parent) %>
  <% else %>
    Not grouped
  <% end %>
</p>

<%= link_to 'Edit', edit_admin_decision_path(@decision), :class=> "button" %>
<%= link_to 'Back', admin_decisions_path, :class=> "button" %>
<br/>
<br/>
<br/>
<br/>
<br/>
<h3>Categories</h3>
<table>
    <tr>
        <td>Identifier</td>
        <td>Name</td>
        <td>Description</td>
        <td></td>
    </tr>
  <% @categories.each do |category| %>
    <tr>
        <td><%= category.identifier %></td>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td>
          <%= link_to 'Show', [:admin, category] %>
          <%= link_to 'Edit', edit_admin_category_path(category), :class=> "button" %>
          <%= link_to 'Destroy', [:admin, category], :confirm => 'Are you sure?', :method => :delete %>
        </td>
    </tr>
  <% end %>
</table>

<%= link_to 'Add new Category', new_admin_decision_category_path(@decision), :class=> "button" %>